# ワークフローの名前
name: Python CI/CD Pipeline

# ワークフローが実行されるトリガーを定義
on:
  # mainブランチへのプッシュ時
  push:
    branches: [ main ]
  # mainブランチに対するプルリクエスト時
  pull_request:
    branches: [ main ]

# 実行される一連のタスク（ジョブ）を定義
jobs:
  build-and-test:
    # ジョブを実行する仮想環境の種類を指定
    runs-on: ubuntu-latest

    # ジョブ内のステップ（実行されるコマンドやアクション）
    steps:
    # 1. リポジトリのコードをチェックアウトする
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Python 3.10 環境をセットアップする
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # 3. 依存ライブラリをインストールする（キャッシュを利用して高速化）
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Pytestを用いてテストを実行する
    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest

    # 5. Dockerイメージをビルドする
    - name: Build Docker image
      run: |
        docker build -t pokemon-ai-tool .